server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost/categoriadb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html